apiVersion: v1
kind: ConfigMap
metadata:
  name: creativeiq-app-config
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_VERSION: "v1"
  CORS_ORIGINS: "http://localhost:3000"
  SNOWFLAKE_ACCOUNT: "REPLACE_WITH_ACCOUNT_IDENTIFIER"
  STORAGE_BUCKET_RAW_ADS: "REPLACE_WITH_BUCKET"
  STORAGE_BUCKET_EXTRACTED: "REPLACE_WITH_BUCKET"
  STORAGE_BUCKET_MODELS: "REPLACE_WITH_BUCKET"
  STORAGE_BUCKET_BRAND_ASSETS: "REPLACE_WITH_BUCKET"
