apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creativeiq-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: creativeiq-api
                port:
                  number: 8000
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: creativeiq-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: creativeiq-frontend
                port:
                  number: 80
