apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: creativeiq

resources:
  - namespace.yaml
  - configmap-app.yaml
  - configmap-frontend-nginx.yaml
  - serviceaccount-api.yaml
  - serviceaccount-decomposition.yaml
  - serviceaccount-profile-engine.yaml
  - serviceaccount-chat.yaml
  - serviceaccount-frontend.yaml
  - deployment-api.yaml
  - deployment-decomposition.yaml
  - deployment-profile-engine.yaml
  - deployment-chat.yaml
  - deployment-frontend.yaml
  - service-api.yaml
  - service-decomposition.yaml
  - service-profile-engine.yaml
  - service-chat.yaml
  - service-frontend.yaml
  - ingress.yaml
  - networkpolicy-api.yaml
  - networkpolicy-decomposition.yaml
  - networkpolicy-profile-engine.yaml
  - networkpolicy-chat.yaml
  - networkpolicy-frontend.yaml
  - hpa-decomposition.yaml
  - external-secrets/externalsecret-app.yaml

commonLabels:
  app.kubernetes.io/part-of: creativeiq
