apiVersion: v1
kind: ServiceAccount
metadata:
  name: creativeiq-profile-engine
  annotations:
    iam.gke.io/gcp-service-account: "creativeiq-profile-engine@creativeiq-493423.iam.gserviceaccount.com"
