apiVersion: v1
kind: Service
metadata:
  name: creativeiq-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: creativeiq-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
