apiVersion: v1
kind: ConfigMap
metadata:
  name: creativeiq-app-config
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
  DEBUG: "true"
  CORS_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
