select
    ad_id,
    brand_id,
    platform,
    title,
    published_at,
    status,
    total_impressions,
    total_clicks,
    total_conversions,
    total_spend,
    total_revenue,
    avg_ctr,
    avg_cpa,
    avg_roas,
    avg_completion_rate,
    hook_type,
    emotional_tone,
    narrative_arc,
    cta_type,
    cta_placement,
    product_prominence,
    human_presence,
    logo_visible,
    text_overlay_style,
    background_setting,
    music_style,
    duration_seconds,
    scene_count,
    motion_intensity,
    text_density,
    face_present_ratio,
    has_music,
    has_voiceover,
    processing_duration_seconds,
    current_timestamp() as computed_at
from {{ ref('int_ads_with_fingerprints') }}

