apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-deployment-api-replicas.yaml
  - path: patch-configmap-prod.yaml

images:
  - name: creativeiq-api
    newName: us-east1-docker.pkg.dev/creativeiq-493423/creativeiq-images/creativeiq-api
    newTag: stable
  - name: creativeiq-decomposition
    newName: us-east1-docker.pkg.dev/creativeiq-493423/creativeiq-images/creativeiq-decomposition
    newTag: stable
  - name: creativeiq-profile-engine
    newName: us-east1-docker.pkg.dev/creativeiq-493423/creativeiq-images/creativeiq-profile-engine
    newTag: stable
  - name: creativeiq-chat
    newName: us-east1-docker.pkg.dev/creativeiq-493423/creativeiq-images/creativeiq-chat
    newTag: stable
  - name: creativeiq-frontend
    newName: us-east1-docker.pkg.dev/creativeiq-493423/creativeiq-images/creativeiq-frontend
    newTag: stable
